default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
# isort
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
  - id: seed-isort-config
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
# flake8
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args: # arguments to configure flake8
        - "--max-line-length=79"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"
        - "--ignore=W503"
        - "--per-file-ignores=lakshmi/lak.py:F811"
# unittest
- repo: local
  hooks:
  - id: unittest
    name: unittest
    entry: python -m unittest discover
    language: python
    additional_dependencies: [click, pyxirr, PyYAML, requests, tabulate, yfinance]
    types: [python]
    pass_filenames: false
